### ISSUE TITLE
Prerequisite for translation

### ISSUE THREAD

**Issue by Galixte** [Alecto/UserTopics#2]
Hi @Alecto,

i’m a french translator, i would translate your extension.

Could you translate this file in english please: https://github.com/Alecto/UserTopics/blob/master/language/ru/UserTopics.php ? (in a new /en/ folder).

**Comment by Alecto** [comment]
Hi, i made EN translation.

**Comment by Galixte** [comment]
Thaks to you, i will translate soon. ;=)
